##########################################################################
# @file prj.conf
# @brief Various MIDI protocol test with the Zephyr SDK
# @note
# adding in some MIDI1 legacy DIN5 serial.  
#
# Code is based on the original midi-usb sample
#
# @author Jan-Willem Smaal <usenet@gispen.org
# @date 20251220
##########################################################################
CONFIG_INPUT=n
CONFIG_LOG=n


##########################################################################
# Tune these settings to reduce the RAM footprint
##########################################################################
CONFIG_IDLE_STACK_SIZE=128
CONFIG_ISR_STACK_SIZE=1024
# Note this one is under the display and cannot be reduced 
#CONFIG_HEAP_MEM_POOL_SIZE=1536



# Let's disable the boot banner because 
# on the FRDM_MCXC242 overlay we use it will go out 
# the MIDI port...  
CONFIG_BOOT_BANNER=n

# Serial port support with IRQ on RX.
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# Sensors (maybe later) 
CONFIG_SENSOR=n
CONFIG_SENSOR_SHELL=n
CONFIG_SENSOR_INFO=n
#CONFIG_VL53L0X_PROXIMITY_THRESHOLD=100
CONFIG_SHT4X=n
CONFIG_FXOS8700=n

# Counters (required) 
CONFIG_COUNTER=y
# For the FRDM_MCXC242 and FRDM_K64F 
CONFIG_COUNTER_NXP_PIT=y
# For the FRDM_MCXA156 board.
CONFIG_COUNTER_MCUX_CTIMER=y 


# GPIO (used for the scope measurements) 
CONFIG_GPIO=y

# Math stuff, try to leave it out because it doesn't fit in the RAM. 
CONFIG_NEWLIB_LIBC=n
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=n
CONFIG_NEWLIB_LIBC_FLOAT_SCANF=n

##########################################################################
# Configure I2C display SH1106 (clone of SSD1306) 
##########################################################################
CONFIG_DISPLAY=y
CONFIG_SSD1306=y

# If we use the board FRDM_MCXA156 we use a different display 
CONFIG_SSD1331=n


# Enable Character Framebuffer (text rendering)
CONFIG_HEAP_MEM_POOL_SIZE=1280  
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y


##########################################################################
# USBD MIDI2.0 device support
##########################################################################
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_MIDI2_CLASS=y
CONFIG_SAMPLE_USBD_PRODUCT="USB MIDI2.0 J-W Smaal"
CONFIG_SAMPLE_USBD_PID=0x0011
CONFIG_USBD_LOG_LEVEL_WRN=n
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=n
CONFIG_MIDI2_UMP_STREAM_RESPONDER=y

# EOF 
